apiVersion: v1
kind: Service
metadata:
  name: tictaktoe-service
  namespace: tictaktoe
  labels:
    app: tictaktoe
spec:
  type: LoadBalancer
  selector:
    app: tictaktoe
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
